# General information about the docs site
site_name: "{{ cookiecutter.project_name }}"
site_url: https://example.com # TODO: change this to the actual documentation site in production
site_author: "{{ cookiecutter.author_name }}"
copyright: "Copyright &copy; {% now 'utc', '%Y' %}, {{ cookiecutter.author_name }}"

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: "{{ cookiecutter.repo_url }}"

# Site navigations
watch:
  - src
nav:
  - Home:
      - index.md
      - usage/installation.md
  # defer to gen-files + literate-nav
  - API references: reference/

# GitHub-related configs
repo_url: "{{ cookiecutter.repo_url }}"
repo_name: "{{ cookiecutter.author_name }}/{{ cookiecutter.repo_name }}"
edit_uri: blob/master/docs/

# Theming with mkdocs-material
theme:
  name: material
  font:
    text: Roboto
    code: JetBrains Mono
  icon:
    repo: fontawesome/brands/gitlab
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: no

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
